security:
    password_hashers:
        App\Security\UserProvider: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        app_users:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_users
            form_login:
                enable_csrf: true
            logout:
                path: /logout

    access_control:
        - { path: ^/profile,      roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/server,       roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/upgrade,      roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/api/bump/,    roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/api/server/,  roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/admin/login,  roles: ROLE_ADMIN }
        - { path: ^/admin/,       roles: ROLE_SUPER_ADMIN }
