twig:
    file_name_pattern: '*.twig'
    globals:
        siteName: nsfwdiscord.me
        titleSuffix: ' - nsfwdiscord.me'
        discordClientID: '%env(DISCORD_CLIENT_ID)%'
        recaptchaSiteKey: '%env(RECAPTCHA_SITE_KEY)%'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
